# SIMULATOR SETTINGS
simulation:
  dt: 4e-3
  substeps : 5
  backend : gpu
  precision : '32'
  performance_mode : True

rigid_options:
  iterations: 10
  ls_iterations: 10
  tolerance: 1e-4
  ls_tolerance: 0.05
  box_box_detection: True
  use_contact_island: True
  use_hibernation: False

box:
  vol : [0.128, 0.128, 0.04]
  wall_thickness : 0.02
  friction : None                           # SET IN DATA_COLLECTION LOOP
material:
  vol : [0.127, 0.127, 0.05]
  shape : None                              # SET IN DATA_COLLECTION LOOP
  particle_size : None                      # SET IN DATA_COLLECTION LOOP
  n_particles : None                        # SET IN DATA_COLLECTION LOOP
  density : None                            # SET IN DATA_COLLECTION LOOP
  friction : None                           # SET IN DATA_COLLECTION LOOP
safety_margin : 0.005

plate:
  speed : 0.125 # m/s
  size : [0.04, 0.002, 0.01]

