script: train_STN_genesis.py
started_at: '2026-06-03T11:35:42'
log_dir: runs_cubes/stn_mse
model:
  type: EulerianSTN
  in_channels: 2
training:
  epochs: 70
  batch_size: 256
  lr: 0.0001
  lr_scheduler: StepLR(step_size=10, gamma=0.5)
  data_augmentation: true
  patience: 10
  improvement_window: 5
loss:
  mse_weight: 1.0
  dice_weight: 0.0
  sharpness_weight: 0.0
  tv_weight: 0.0
  mass_weight: 0.0
  add_weight: 0.0
  remove_weight: 0.0
  pos_weight_bce: 20.0
  jac_weight: 0.1
data:
  folders:
  - corl/cube
  resolution_scale: 0.5
resume:
  resumed_from: null
  fresh_start: false
